# -*- coding: utf-8 -*-
"""HR_Attrition_End_to_End_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9SvT01ga01rkw736qNqu6Rp_Yu9Su4U

Import Libraries
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

"""Load Dataset"""

df= pd.read_csv("/content/HumanResources.csv")
df

df['Atrition']=df['termination_date'].notna().astype(int)

"""Drop unnecessary columns"""

df.drop(columns=['employee_id','first_name','last_name','termination_date'],inplace=True)

"""Date Feature Engineering"""

df['hire_date']=pd.to_datetime(df['hire_date'])
df['birth_date']=pd.to_datetime(df['birth_date'])

df['age']=(pd.Timestamp.today() - df['birth_date']).dt.days//365
df['experience_years']=(pd.Timestamp.today() - df['hire_date']).dt.days//365

df.drop(columns=['hire_date','birth_date'],inplace=True)

"""Encode Binary & Ordinal Features"""

df['gender']=df['gender'].map({'Male':1,'Female':0})
df['overtime']=df['overtime'].map({'Yes':1,'No':0})

education_map={'High School':1, 'Bachelor':2, 'Master':3, 'PhD':4}
df['education_level']=df['education_level'].map(education_map)

peerformance_map={
    'Needs Improvement':1,
    'Satisfactory':2,
    'Good':3,
    'Excellent':4
}
df['performance_rating']=df['performance_rating'].map(peerformance_map)

"""One-Hot Encode Nominal Ffeatures"""

df=pd.get_dummies(
    df,
    columns=['state','city','department','job_title'],
    drop_first=True
)

"""Split data"""

x=df.drop('Atrition',axis=1)
y=df['Atrition']

X_train,X_test,y_train,y_test=train_test_split(

x,y,test_size=0.2, random_state=42, stratify=y)

"""Feature Scaling"""

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

"""Train Model"""

model=RandomForestClassifier(random_state=42)
model.fit(X_train,y_train)

"""Evaluation"""

y_pred=model.predict(X_test)
print("Accuracy:", accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

"""Exploratary Data Analysis"""

import matplotlib.pyplot as plt
import seaborn as sns

"""Atrrition Distribution"""

sns.countplot(x='Atrition',data=df)
plt.title('Atrrition Distribution')
plt.show()

"""Gender vs Atrrition"""

sns.countplot(x='gender',hue='Atrition',data=df)
plt.title('Gender vs Atrrition')
plt.show

dept_attr=df.groupby('department_Sales')['Atrition'].mean()
dept_attr.plot(kind='bar')
plt.title('Department-wise Attrition Rate (sample)')
plt.ylabel('Attrition Rate')
plt.show()

sns.histplot(data=df['salary'],kde=True)
plt.title('Salary Distribution')
plt.show()

sns.boxplot(x='Atrition',y='salary',data=df)
plt.title('Salary vs Atrrition')
plt.show()

"""Age Distribution"""

sns.histplot(data=df['age'],kde=True)
plt.title('Age Distribution')
plt.show()

sns.boxplot(x='Atrition',y='experience_years',data=df)
plt.title('Experience vs Atrrition')
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(),cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

df['salary_difference'] = df['salary'] - df['base_salary']

df.groupby('Atrition')['salary_difference'].mean()

sns.barplot(x='Atrition', y='salary_difference', data=df)
plt.title('Average Salary Difference by Attrition Status')
plt.xlabel('Attrition (0 = No, 1 = Yes)')
plt.ylabel('Average Salary Difference')
plt.show()

